export const exchangeMapper = Object.freeze({
  "American Stock Exchange": "AMEX",
  "Australian Securities Exchange": "ASX",
  "Chicago Futures Exchange": "CFE",
  "EUREX Futures Exchange": "EUREX",
  "Foreign Exchange": "FOREX",
  "Global Indices": "INDEX",
  "LIFFE Futures and Options": "LIFFE",
  "London Stock Exchange": "LSE",
  "Minneapolis Grain Exchange": "MGEX",
  "NASDAQ Stock Exchange": "NASDAQ",
  "New York Board of Trade": "NYBOT",
  "New York Stock Exchange": "NYSE",
  "OTC Bulletin Board": "OTCBB",
  "Singapore Stock Exchange": "SGX",
  "Tokyo Stock Exchange": "TSX",
  "Toronto Venture Exchange": "TSXV",
  "Mutual Funds": "USMF",
  "Winnipeg Commodity Exchange": "WCE",
});
